# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu12"
  config.vm.provider "virtualbox" do |v|
    v.memory = 1024
  end
  config.vm.box_url = 'https://cloud-images.ubuntu.com/vagrant/precise/current/precise-server-cloudimg-amd64-vagrant-disk1.box'
  config.vm.hostname = 'rxjs-labs'
  config.vm.network "forwarded_port", guest: 80, host: 9080
  config.vm.network "forwarded_port", guest: 9000, host: 9000
  
  config.vm.synced_folder ".", "/project"
  config.vm.synced_folder "../_common", "/_common"
  
  config.vm.provision "shell", inline: "sh /project/provisioner.sh"
end
